# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: rrha2rGtt5kORJnycNL94nzmNjYpMWEn
            client-secret: UBA_i3YlP8rUBlV4dkwS6f0Yszlv1aKeuXei1KFEVPuV2iyxdbLvLQHtshNUYa-_
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-w6ere6nb.us.auth0.com/